import os
import pandas as pd

# ============================================================
# STEP 8B
# Initialize canonical Power BI event feeder contracts
#
# IMPORTANT:
# - Creates the 7 canonical event/lineage CSVs.
# - Preserves existing rows if a file already exists.
# - Adds missing canonical columns without deleting existing data.
# - Does NOT modify powerbi_trades.csv.
# - Does NOT modify the Trading OS core.
# - OpportunityID is generated by the operational/orchestration
#   layer later, never by Power BI.
# ============================================================

BASE_DIR = (
    r"D:\OBSIDIAN VAULT\halal-trading-os"
    r"\Peripheral Ecosystem\data_cache\powerbi"
)

os.makedirs(BASE_DIR, exist_ok=True)


# ============================================================
# CANONICAL CONTRACTS
# ============================================================

CONTRACTS = {

    # --------------------------------------------------------
    # 1. Periodic fundamental + Shariah eligibility snapshot
    # Grain: one stock × one screening cycle
    # --------------------------------------------------------
    "powerbi_screening.csv": [
        "ScreeningRecordID",
        "ScreeningCycleID",
        "Symbol",
        "ScreeningTimestamp",
        "FundamentalStatus",
        "MarketCap",
        "ROE",
        "DebtEquity",
        "CurrentRatio",
        "QuickRatio",
        "OtherIncomePct",
        "ShariahStatus",
        "ShariahProvider",
        "EligibilityStatus",
        "ValidFrom",
        "ValidTo",
        "Source",
    ],

    # --------------------------------------------------------
    # 2. Chartink scanner events
    # Grain: one scanner event
    # --------------------------------------------------------
    "powerbi_scanner_events.csv": [
        "ScannerEventID",
        "OpportunityID",
        "Symbol",
        "ScanTimestamp",
        "Provider",
        "ScannerName",
        "SignalType",
        "ScannerStatus",
        "ScannerValue",
        "SourceEventID",
    ],

    # --------------------------------------------------------
    # 3. TradingView technical observations
    # Grain: one technical observation / confirmation event
    # --------------------------------------------------------
    "powerbi_technical_events.csv": [
        "TechnicalEventID",
        "OpportunityID",
        "Symbol",
        "Timestamp",
        "Provider",
        "Timeframe",
        "IndicatorState",
        "EMA20",
        "EMA50",
        "VWAP",
        "RSI50",
        "RSI10",
        "AVPUsed",
        "FRVPUsed",
        "PivotContext",
        "Confirmation",
        "SourceEventID",
    ],

    # --------------------------------------------------------
    # 4. NSE / market-context snapshots
    # Grain: one market snapshot
    # --------------------------------------------------------
    "powerbi_market_context.csv": [
        "MarketSnapshotID",
        "OpportunityID",
        "Timestamp",
        "NiftyTrend",
        "IndiaVIX",
        "Advances",
        "Declines",
        "MarketRegime",
        "Source",
    ],

    # --------------------------------------------------------
    # 5. Governance / risk / audit events
    # Grain: one audit event
    # --------------------------------------------------------
    "powerbi_audits.csv": [
        "AuditID",
        "OpportunityID",
        "Timestamp",
        "Component",
        "AuditType",
        "Decision",
        "Severity",
        "Rule",
        "Result",
        "Reason",
        "InputSource",
        "Model",
        "ReadOnly",
        "LiveAutoExecution",
        "OrderCapability",
        "ExecutionAuthority",
    ],

    # --------------------------------------------------------
    # 6. Execution observations
    # Grain: one execution event
    # --------------------------------------------------------
    "powerbi_execution_events.csv": [
        "ExecutionEventID",
        "OpportunityID",
        "TradeID",
        "Timestamp",
        "ExecutionSource",
        "ExecutionType",
        "Status",
        "FillPrice",
        "Quantity",
        "CapitalUsed",
        "StopLoss",
        "Target",
        "Notes",
    ],

    # --------------------------------------------------------
    # 7. Opportunity → Trade lineage bridge
    # Grain: one lineage relationship
    # --------------------------------------------------------
    "powerbi_opportunity_trade_bridge.csv": [
        "BridgeID",
        "OpportunityID",
        "TradeID",
        "LinkType",
        "FinalStage",
        "RejectionReason",
        "LinkTimestamp",
    ],
}


# ============================================================
# HELPERS
# ============================================================

def initialize_contract(filename, columns):
    path = os.path.join(BASE_DIR, filename)

    # --------------------------------------------------------
    # New file
    # --------------------------------------------------------
    if not os.path.exists(path):
        pd.DataFrame(columns=columns).to_csv(
            path,
            index=False,
            encoding="utf-8-sig"
        )

        print(f"CREATED : {filename}")
        return {
            "status": "CREATED",
            "rows": 0,
            "path": path,
        }

    # --------------------------------------------------------
    # Existing file
    # --------------------------------------------------------
    try:
        df = pd.read_csv(
            path,
            dtype=str,
            keep_default_na=False
        )
    except Exception as exc:
        raise RuntimeError(
            f"Could not read existing {filename}: {exc}"
        )

    existing_columns = list(df.columns)

    # Add missing canonical columns
    added_columns = []

    for column in columns:
        if column not in df.columns:
            df[column] = ""
            added_columns.append(column)

    # Canonical columns first
    extra_columns = [
        column
        for column in df.columns
        if column not in columns
    ]

    final_columns = columns + extra_columns

    df = df[final_columns]

    # Save non-destructively
    df.to_csv(
        path,
        index=False,
        encoding="utf-8-sig"
    )

    if added_columns:
        print(
            f"UPDATED : {filename} "
            f"(added {len(added_columns)} missing column(s))"
        )
        for column in added_columns:
            print(f"           + {column}")
    else:
        print(f"EXISTS  : {filename} (schema already present)")

    return {
        "status": "UPDATED" if added_columns else "EXISTS",
        "rows": len(df),
        "path": path,
        "columns": final_columns,
        "added_columns": added_columns,
    }


# ============================================================
# INITIALIZE ALL CONTRACTS
# ============================================================

print("=" * 80)
print("HALAL TRADING OS — POWER BI EVENT CONTRACT INITIALIZATION")
print("=" * 80)
print()
print(f"Directory: {BASE_DIR}")
print()

results = {}

for filename, columns in CONTRACTS.items():
    results[filename] = initialize_contract(
        filename,
        columns
    )

    print()


# ============================================================
# VERIFY EXISTING TRADE LEDGER
# ============================================================

TRADES_FILE = os.path.join(
    BASE_DIR,
    "powerbi_trades.csv"
)

print("=" * 80)
print("EXISTING TRADE LEDGER CHECK")
print("=" * 80)

if os.path.exists(TRADES_FILE):

    trades = pd.read_csv(
        TRADES_FILE,
        dtype=str,
        keep_default_na=False
    )

    print("powerbi_trades.csv : PRESENT")
    print(f"Rows               : {len(trades)}")
    print(f"Columns            : {len(trades.columns)}")
    print("Modification       : NONE")

else:
    print("WARNING: powerbi_trades.csv not found.")


# ============================================================
# VERIFY OPPORTUNITY ID RULE
# ============================================================

print()
print("=" * 80)
print("OPPORTUNITY ID CONTRACT")
print("=" * 80)

print("Format:")
print("  OPP-YYYYMMDD-NNNN")

print()
print("Examples:")
print("  OPP-20260921-0001")
print("  OPP-20260921-0002")

print()
print("Generation authority:")
print("  Trading OS orchestration layer")

print()
print("Power BI responsibility:")
print("  Store, relate, filter, and analyze")
print("  NEVER generate OpportunityID")


# ============================================================
# GOVERNANCE CHECK
# ============================================================

print()
print("=" * 80)
print("GOVERNANCE")
print("=" * 80)

print("READ_ONLY              = True")
print("LIVE_AUTO_EXECUTION    = False")
print("ORDER_CAPABILITY       = NONE")
print("EXECUTION_AUTHORITY    = NONE")


# ============================================================
# FINAL FILE VERIFICATION
# ============================================================

print()
print("=" * 80)
print("FINAL VERIFICATION")
print("=" * 80)

for filename, columns in CONTRACTS.items():

    path = os.path.join(
        BASE_DIR,
        filename
    )

    exists = os.path.exists(path)

    if exists:
        df = pd.read_csv(
            path,
            dtype=str,
            keep_default_na=False
        )

        missing = [
            column
            for column in columns
            if column not in df.columns
        ]

        print(
            f"{filename:40} "
            f"exists={exists} "
            f"rows={len(df):4d} "
            f"columns={len(df.columns):2d} "
            f"schema={'PASS' if not missing else 'FAIL'}"
        )

        if missing:
            print(
                "  Missing:",
                ", ".join(missing)
            )
    else:
        print(
            f"{filename:40} "
            f"exists=False"
        )

print()
print("=" * 80)
print("STEP 8B COMPLETE")
print("=" * 80)

print()
print("No OpportunityID values were generated.")
print("No signal, scanner, technical, market, audit, or execution")
print("records were fabricated.")
print("Existing trade data was not modified.")
